version: '2'

services:
  anaconda:
    image: continuumio/anaconda3:2019.10
    volumes:
    - ./src:/src

  jupyter:
    image: continuumio/anaconda3:2019.10
    volumes:
    - ./notebooks:/opt/notebooks
    - ./data:/opt/data
    ports:
    - 8888:8888
    command: /bin/bash -c "/opt/conda/bin/conda install jupyter -y --quiet && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root"
